name: Prettier
on: pull_request
jobs:
  webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - run: npm install prettier
      - run: npm run check-format
      - name: Set status 'success'
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/statuses/:sha
          sha: ${{ github.event.pull_request.head.sha }}
          state: success
          context: Prettier Check
          description: Prettier check passed
          token: ${{ secrets.GITHUB_TOKEN }}
